name: CI/CD Pipeline testing on build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: getting the username
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-image-CI/CD-image

      - name: build image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .

      - name: push image to DockerHub
        run:
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest



